services:
  - type: web
    name: church-app-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    workingDirectory: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3